title: ðŸ Shoehive
description: >- 
  Shoehive is an extensible, WebSocket-based multiplayer game framework designed for 
  real-time, event-driven gameplay. It provides a player management system, message 
  routing and structured table handling, allowing developers to focus on building 
  their own game logic while leveraging a powerful core.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://shoehive.jtay.co.uk"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Navigation structure
aux_links_new_tab: true
aux_links:
  GitHub:
    - https://github.com/jtay/shoehive
  NPM:
    - https://www.npmjs.com/package/shoehive

# Include generated API documentation files in the build
include:
  - pages/api/generated


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jtay/shoehive" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately